# Generated by Django 3.1.7 on 2021-02-24 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='catmat',
            field=models.IntegerField(unique=True),
        ),
    ]
