# Generated by Django 3.1.7 on 2021-03-10 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_auto_20210310_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidademedida',
            name='unidade_medida',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
